[project]
name = "backend"
version = "0.1.0"
description = "OCR Backend"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "psycopg2-binary>=2.9.9",
    "sqlalchemy>=2.0.27",
    "python-multipart>=0.0.9",
    "langchain-community>=0.4.1",
    "langchain-ollama>=1.0.1",
    "chromadb>=1.5.1",
    "pypdf>=6.7.3",
    "httpx>=0.28.1",
    "fastapi>=0.133.1",
    "boto3>=1.42.58",
    "ruff>=0.1.0",
    "easyocr>=1.7.1",
    "Pillow>=10.3.0",
    "numpy>=1.26.4",
    "PyMuPDF>=1.23.26",
]
