services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      network: host
    image: ocr-project-frontend
    ports:
      - "8501:8501"
    networks:
      - frontend-net
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      network: host
    image: ocr-project-backend
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresdb:5432/${POSTGRES_DB}
      - ML_SERVICE_URL=http://ml-service:8001
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    volumes:
      - ./storage:/app/storage 
    networks:
      - frontend-net
      - backend-net
    depends_on:
      postgresdb:
        condition: service_healthy
      chromadb:
        condition: service_started


  ml-service:
    build:
      context: .
      dockerfile: ml-service/Dockerfile
      network: host
    image: ocr-project-ml-service
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresdb:5432/${POSTGRES_DB}
    volumes:
      - ./storage:/app/storage
    networks:
      - backend-net
    depends_on:
      - chromadb
      - postgresdb
      

  chromadb:
    image: chromadb/chroma:latest
    restart: always
    volumes:
      - chroma_data:/chroma/data
    ports:
      - "8008:8000"
    networks:
      - backend-net

  postgresdb:
    image: postgres:17-bookworm
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  frontend-net:
  backend-net:

volumes:
  postgres_data:
  chroma_data: