services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000
    image: lease-lens-frontend
    ports:
      - "80:80"
    networks:
      - frontend-net
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: lease-lens-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresdb:5432/${POSTGRES_DB}
      - ML_SERVICE_URL=http://ml-service:8000
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET=artifacts
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
    networks:
      - frontend-net
      - backend-net
    depends_on:
      postgresdb:
        condition: service_healthy
      minio:
        condition: service_started
      ml-service:
        condition: service_started

  ml-service:
    build:
      context: .
      dockerfile: ml-service/Dockerfile
    image: lease-lens-ml-service
    environment:
      - PYTHONPATH=/app
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresdb:5432/${POSTGRES_DB}
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET=artifacts
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
      - BACKEND_INTERNAL_URL=http://backend:8000
    networks:
      - backend-net
    depends_on:
      - chromadb
      - ollama
    env_file:
      - .env

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    volumes:
      - ./ollama_storage:/root/.ollama
    networks:
      - backend-net

  chromadb:
    image: chromadb/chroma:latest
    restart: always
    volumes:
      - chroma_data:/chroma/data
    networks:
      - backend-net

  postgresdb:
    image: postgres:17-bookworm
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama-pull-models:
    image: curlimages/curl:latest
    container_name: ollama-pull-models
    networks:
      - backend-net
    depends_on:
      ollama:
        condition: service_started
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "
      echo 'Esperando a que Ollama responda...';
      until curl -s http://ollama:11434/api/tags > /dev/null; do
        sleep 5;
      done;
      echo 'Descargando Llama 3.1:8b...';
      curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"llama3.1:8b\"}';
      echo 'Descargando Nomic Embed Text...';
      curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"nomic-embed-text\"}';
      echo 'Modelos listos.';
      "

  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000" # API
      - "9001:9001" # Consola UI
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    networks:
      - backend-net
    command: server /data --address ":9000" --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - backend-net
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}) do echo '...waiting for minio...' && sleep 1; done;
      /usr/bin/mc mb --ignore-existing local/artifacts; # <--- AÑADE ESTO
      /usr/bin/mc policy set public local/artifacts;
      exit 0;"

  seed_admin_user:
    image: lease-lens-backend 
    command: ["uv", "run", "python", "-m", "src.create_default_admin"]
    networks:
      - backend-net
    depends_on:
      postgresdb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresdb:5432/${POSTGRES_DB}
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
    restart: "no" 

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lease-lens-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80" 
    networks:
      - backend-net
    depends_on:
      - postgresdb
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  frontend-net:
  backend-net:

volumes:
  postgres_data:
  chroma_data:
  minio_data:
  pgadmin_data: