[project]
name = "leaselens-backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "uvicorn[standard]",
    "httpx",
    "fastapi",
    "sqlalchemy",
    "minio",
    "pydantic-settings",
    "asyncpg",
    "python-jose[cryptography]",
    "pillow",
    "pgvector",
    "passlib[bcrypt]",
    "bcrypt==4.3.0",
    "PyMuPDF",
    "opencv-python-headless",
    "python-multipart",
    "greenlet",
]